### Day Objectives:
     - pandas
     
###### Pandas:
     - pandas is derived from panel-data
     - it is an open source python library that produces high performance 
       data manipulation and data analysing
#### usecases:
    - data cleaning
    - data transformation
    - data analysis
#### data structures in pandas
    - pandas series
        syntax:
            pandas.Series(data,index,dtype)
    - pandas dataframes

In [18]:
import pandas as pd
import numpy as np
pd.__version__

'0.24.2'

In [2]:
s=pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
s1

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
#### slicing
print(s1[0])
print(s1[0],s1[1])
print(s1[1:])
print(s1['a':'d'])

1
1 2
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64

In [9]:
s1.index=['a1','a2','a3','a4']
s1

a1    1
a2    2
a3    3
a4    4
dtype: int64

In [10]:
marks={'maths':90,'phy':80,'sci':70}
marks

{'maths': 90, 'phy': 80, 'sci': 70}

In [11]:
pd.Series(marks)

maths    90
phy      80
sci      70
dtype: int64

In [12]:
pd.date_range('02-10-2020','10-10-2020')

DatetimeIndex(['2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13',
               '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17',
               '2020-02-18', '2020-02-19',
               ...
               '2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04',
               '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10'],
              dtype='datetime64[ns]', length=244, freq='D')

In [13]:
pd.date_range('2020-10-02','2020-10-10')

DatetimeIndex(['2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05',
               '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09',
               '2020-10-10'],
              dtype='datetime64[ns]', freq='D')

In [15]:
date=pd.date_range('2020-10-02',periods=4)
date

DatetimeIndex(['2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05'], dtype='datetime64[ns]', freq='D')

In [16]:
temp=pd.Series([78,90,89,56],pd.date_range('2020-10-02',periods=4))
temp

2020-10-02    78
2020-10-03    90
2020-10-04    89
2020-10-05    56
Freq: D, dtype: int64

In [17]:
temp=pd.Series([78,90,89,56],index=date)
temp

2020-10-02    78
2020-10-03    90
2020-10-04    89
2020-10-05    56
Freq: D, dtype: int64

In [21]:
pd.Series(np.arange(1,10))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int32

### pandas datafrmes
- convertion of table format
- creating dataframes from dictionary
- creating dataframes from arrays

In [22]:
#### from dictionary
studentmarks={"names":['ram','asha','giri'],
              "maths":[23,45,67],
              "sci":[56,36,98],
              "eng":[23,56,78]}
studentmarks

{'names': ['ram', 'asha', 'giri'],
 'maths': [23, 45, 67],
 'sci': [56, 36, 98],
 'eng': [23, 56, 78]}

In [23]:
pd.DataFrame(studentmarks)

  names  maths  sci  eng
0   ram     23   56   23
1  asha     45   36   56
2  giri     67   98   78

In [25]:
### from arrays
a1=np.array([['ram',23,45,67],['asha',56,36,98]])
pd.DataFrame(a1,columns=['name','maths','sci','eng'])

   name maths sci eng
0   ram    23  45  67
1  asha    56  36  98

In [27]:
a1=np.array([['ram',23,45,67],['asha',56,36,98]])
pd.DataFrame(a1,columns=['name','maths','sci','eng'],index=['1','2'])

   name maths sci eng
1   ram    23  45  67
2  asha    56  36  98

## read a csv file
    - pd.read_csv()

In [28]:
df=pd.read_csv('cars.csv')
df

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,2013,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,2013,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
11,2014,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
12,2014,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
13,2014,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
14,2014,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
15,2014,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
16,2014,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
17,2014,TESLA,MODEL S (60 kWh battery),FULL-SIZE,225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,2014,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,2014,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
20,2015,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,NaN,130,4
21,2015,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
22,2015,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
23,2015,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,NaN,149,4
24,2015,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
25,2015,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
26,2015,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
27,2015,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
28,2015,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,2015,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,2015,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,2015,TESLA,MODEL S 70D,FULL-SIZE,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,2015,TESLA,MODEL S 85D/90D,FULL-SIZE,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,2015,TESLA,MODEL S P85D/P90D,FULL-SIZE,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
34,2016,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,10.0,130,4
35,2016,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,10.0,131,7
36,2016,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,10.0,122,4
37,2016,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,10.0,149,4
38,2016,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,10.0,100,7
39,2016,NISSAN,LEAF (24 kWh battery),MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,10.0,135,5
40,2016,NISSAN,LEAF (30 kWh battery),MID-SIZE,80,A1,B,17.0,20.7,18.6,1.9,2.3,2.1,0,10.0,172,6
41,2016,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
42,2016,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,2016,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,2016,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,2016,TESLA,MODEL S 70D,FULL-SIZE,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,2016,TESLA,MODEL S 85D/90D,FULL-SIZE,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [29]:
df.columns

Index(['YEAR', 'Make', 'Model', 'Size', '(kW)', 'Unnamed: 5', 'TYPE',
       'CITY (kWh/100 km)', 'HWY (kWh/100 km)', 'COMB (kWh/100 km)',
       'CITY (Le/100 km)', 'HWY (Le/100 km)', 'COMB (Le/100 km)', '(g/km)',
       'RATING', '(km)', 'TIME (h)'],
      dtype='object')

In [30]:
df.values

array([[2012, 'MITSUBISHI', 'i-MiEV', 'SUBCOMPACT', 49, 'A1', 'B', 16.9,
        21.4, 18.7, 1.9, 2.4, 2.1, 0, nan, 100, 7],
       [2012, 'NISSAN', 'LEAF', 'MID-SIZE', 80, 'A1', 'B', 19.3, 23.0,
        21.1, 2.2, 2.6, 2.4, 0, nan, 117, 7],
       [2013, 'FORD', 'FOCUS ELECTRIC', 'COMPACT', 107, 'A1', 'B', 19.0,
        21.1, 20.0, 2.1, 2.4, 2.2, 0, nan, 122, 4],
       [2013, 'MITSUBISHI', 'i-MiEV', 'SUBCOMPACT', 49, 'A1', 'B', 16.9,
        21.4, 18.7, 1.9, 2.4, 2.1, 0, nan, 100, 7],
       [2013, 'NISSAN', 'LEAF', 'MID-SIZE', 80, 'A1', 'B', 19.3, 23.0,
        21.1, 2.2, 2.6, 2.4, 0, nan, 117, 7],
       [2013, 'SMART', 'FORTWO ELECTRIC DRIVE CABRIOLET', 'TWO-SEATER',
        35, 'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2013, 'SMART', 'FORTWO ELECTRIC DRIVE COUPE', 'TWO-SEATER', 35,
        'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2013, 'TESLA', 'MODEL S (40 kWh battery)', 'FULL-SIZE', 270,
        'A1', 'B', 22.4, 21.9, 22.2, 2.5, 2.5, 2.5, 0, nan, 224, 6],
       [2013, 'TESLA', 'MODEL S (60 kWh battery)', 'FULL-SIZE', 270,
        'A1', 'B', 22.2, 21.7, 21.9, 2.5, 2.4, 2.5, 0, nan, 335, 10],
       [2013, 'TESLA', 'MODEL S (85 kWh battery)', 'FULL-SIZE', 270,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 426, 12],
       [2013, 'TESLA', 'MODEL S PERFORMANCE', 'FULL-SIZE', 310, 'A1',
        'B', 23.9, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 426, 12],
       [2014, 'CHEVROLET', 'SPARK EV', 'SUBCOMPACT', 104, 'A1', 'B',
        16.0, 19.6, 17.8, 1.8, 2.2, 2.0, 0, nan, 131, 7],
       [2014, 'FORD', 'FOCUS ELECTRIC', 'COMPACT', 107, 'A1', 'B', 19.0,
        21.1, 20.0, 2.1, 2.4, 2.2, 0, nan, 122, 4],
       [2014, 'MITSUBISHI', 'i-MiEV', 'SUBCOMPACT', 49, 'A1', 'B', 16.9,
        21.4, 18.7, 1.9, 2.4, 2.1, 0, nan, 100, 7],
       [2014, 'NISSAN', 'LEAF', 'MID-SIZE', 80, 'A1', 'B', 16.5, 20.8,
        18.4, 1.9, 2.3, 2.1, 0, nan, 135, 5],
       [2014, 'SMART', 'FORTWO ELECTRIC DRIVE CABRIOLET', 'TWO-SEATER',
        35, 'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2014, 'SMART', 'FORTWO ELECTRIC DRIVE COUPE', 'TWO-SEATER', 35,
        'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2014, 'TESLA', 'MODEL S (60 kWh battery)', 'FULL-SIZE', 225,
        'A1', 'B', 22.2, 21.7, 21.9, 2.5, 2.4, 2.5, 0, nan, 335, 10],
       [2014, 'TESLA', 'MODEL S (85 kWh battery)', 'FULL-SIZE', 270,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 426, 12],
       [2014, 'TESLA', 'MODEL S PERFORMANCE', 'FULL-SIZE', 310, 'A1',
        'B', 23.9, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 426, 12],
       [2015, 'BMW', 'i3', 'SUBCOMPACT', 125, 'A1', 'B', 15.2, 18.8,
        16.8, 1.7, 2.1, 1.9, 0, nan, 130, 4],
       [2015, 'CHEVROLET', 'SPARK EV', 'SUBCOMPACT', 104, 'A1', 'B',
        16.0, 19.6, 17.8, 1.8, 2.2, 2.0, 0, nan, 131, 7],
       [2015, 'FORD', 'FOCUS ELECTRIC', 'COMPACT', 107, 'A1', 'B', 19.0,
        21.1, 20.0, 2.1, 2.4, 2.2, 0, nan, 122, 4],
       [2015, 'KIA', 'SOUL EV', 'STATION WAGON - SMALL', 81, 'A1', 'B',
        17.5, 22.7, 19.9, 2.0, 2.6, 2.2, 0, nan, 149, 4],
       [2015, 'MITSUBISHI', 'i-MiEV', 'SUBCOMPACT', 49, 'A1', 'B', 16.9,
        21.4, 18.7, 1.9, 2.4, 2.1, 0, nan, 100, 7],
       [2015, 'NISSAN', 'LEAF', 'MID-SIZE', 80, 'A1', 'B', 16.5, 20.8,
        18.4, 1.9, 2.3, 2.1, 0, nan, 135, 5],
       [2015, 'SMART', 'FORTWO ELECTRIC DRIVE CABRIOLET', 'TWO-SEATER',
        35, 'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2015, 'SMART', 'FORTWO ELECTRIC DRIVE COUPE', 'TWO-SEATER', 35,
        'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, nan, 109, 8],
       [2015, 'TESLA', 'MODEL S (60 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 22.2, 21.7, 21.9, 2.5, 2.4, 2.5, 0, nan, 335, 10],
       [2015, 'TESLA', 'MODEL S (70 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 377, 12],
       [2015, 'TESLA', 'MODEL S (85/90 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, nan, 426, 12],
       [2015, 'TESLA', 'MODEL S 70D', 'FULL-SIZE', 280, 'A1', 'B', 20.8,
        20.6, 20.7, 2.3, 2.3, 2.3, 0, nan, 386, 12],
       [2015, 'TESLA', 'MODEL S 85D/90D', 'FULL-SIZE', 280, 'A1', 'B',
        22.0, 19.8, 21.0, 2.5, 2.2, 2.4, 0, nan, 435, 12],
       [2015, 'TESLA', 'MODEL S P85D/P90D', 'FULL-SIZE', 515, 'A1', 'B',
        23.4, 21.5, 22.5, 2.6, 2.4, 2.5, 0, nan, 407, 12],
       [2016, 'BMW', 'i3', 'SUBCOMPACT', 125, 'A1', 'B', 15.2, 18.8,
        16.8, 1.7, 2.1, 1.9, 0, 10.0, 130, 4],
       [2016, 'CHEVROLET', 'SPARK EV', 'SUBCOMPACT', 104, 'A1', 'B',
        16.0, 19.6, 17.8, 1.8, 2.2, 2.0, 0, 10.0, 131, 7],
       [2016, 'FORD', 'FOCUS ELECTRIC', 'COMPACT', 107, 'A1', 'B', 19.0,
        21.1, 20.0, 2.1, 2.4, 2.2, 0, 10.0, 122, 4],
       [2016, 'KIA', 'SOUL EV', 'STATION WAGON - SMALL', 81, 'A1', 'B',
        17.5, 22.7, 19.9, 2.0, 2.6, 2.2, 0, 10.0, 149, 4],
       [2016, 'MITSUBISHI', 'i-MiEV', 'SUBCOMPACT', 49, 'A1', 'B', 16.9,
        21.4, 18.7, 1.9, 2.4, 2.1, 0, 10.0, 100, 7],
       [2016, 'NISSAN', 'LEAF (24 kWh battery)', 'MID-SIZE', 80, 'A1',
        'B', 16.5, 20.8, 18.4, 1.9, 2.3, 2.1, 0, 10.0, 135, 5],
       [2016, 'NISSAN', 'LEAF (30 kWh battery)', 'MID-SIZE', 80, 'A1',
        'B', 17.0, 20.7, 18.6, 1.9, 2.3, 2.1, 0, 10.0, 172, 6],
       [2016, 'SMART', 'FORTWO ELECTRIC DRIVE CABRIOLET', 'TWO-SEATER',
        35, 'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, 10.0, 109, 8],
       [2016, 'SMART', 'FORTWO ELECTRIC DRIVE COUPE', 'TWO-SEATER', 35,
        'A1', 'B', 17.2, 22.5, 19.6, 1.9, 2.5, 2.2, 0, 10.0, 109, 8],
       [2016, 'TESLA', 'MODEL S (60 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 22.2, 21.7, 21.9, 2.5, 2.4, 2.5, 0, 10.0, 335, 10],
       [2016, 'TESLA', 'MODEL S (70 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, 10.0, 377, 12],
       [2016, 'TESLA', 'MODEL S (85/90 kWh battery)', 'FULL-SIZE', 283,
        'A1', 'B', 23.8, 23.2, 23.6, 2.7, 2.6, 2.6, 0, 10.0, 426, 12],
       [2016, 'TESLA', 'MODEL S 70D', 'FULL-SIZE', 386, 'A1', 'B', 20.8,
        20.6, 20.7, 2.3, 2.3, 2.3, 0, 10.0, 386, 12],
       [2016, 'TESLA', 'MODEL S 85D/90D', 'FULL-SIZE', 386, 'A1', 'B',
        22.0, 19.8, 21.0, 2.5, 2.2, 2.4, 0, 10.0, 435, 12],
       [2016, 'TESLA', 'MODEL S 90D (Refresh)', 'FULL-SIZE', 386, 'A1',
        'B', 20.8, 19.7, 20.3, 2.3, 2.2, 2.3, 0, 10.0, 473, 12],
       [2016, 'TESLA', 'MODEL S P85D/P90D', 'FULL-SIZE', 568, 'A1', 'B',
        23.4, 21.5, 22.5, 2.6, 2.4, 2.5, 0, 10.0, 407, 12],
       [2016, 'TESLA', 'MODEL S P90D (Refresh)', 'FULL-SIZE', 568, 'A1',
        'B', 22.9, 21.0, 22.1, 2.6, 2.4, 2.5, 0, 10.0, 435, 12],
       [2016, 'TESLA', 'MODEL X 90D', 'SUV - STANDARD', 386, 'A1', 'B',
        23.2, 22.2, 22.7, 2.6, 2.5, 2.6, 0, 10.0, 414, 12],
       [2016, 'TESLA', 'MODEL X P90D', 'SUV - STANDARD', 568, 'A1', 'B',
        23.6, 23.3, 23.5, 2.7, 2.6, 2.6, 0, 10.0, 402, 12]], dtype=object)

In [32]:
df[['Model','Make']]

                              Model        Make
0                            i-MiEV  MITSUBISHI
1                              LEAF      NISSAN
2                    FOCUS ELECTRIC        FORD
3                            i-MiEV  MITSUBISHI
4                              LEAF      NISSAN
5   FORTWO ELECTRIC DRIVE CABRIOLET       SMART
6       FORTWO ELECTRIC DRIVE COUPE       SMART
7          MODEL S (40 kWh battery)       TESLA
8          MODEL S (60 kWh battery)       TESLA
9          MODEL S (85 kWh battery)       TESLA
10              MODEL S PERFORMANCE       TESLA
11                         SPARK EV   CHEVROLET
12                   FOCUS ELECTRIC        FORD
13                           i-MiEV  MITSUBISHI
14                             LEAF      NISSAN
15  FORTWO ELECTRIC DRIVE CABRIOLET       SMART
16      FORTWO ELECTRIC DRIVE COUPE       SMART
17         MODEL S (60 kWh battery)       TESLA
18         MODEL S (85 kWh battery)       TESLA
19              MODEL S PERFORMANCE       TESLA
20                               i3         BMW
21                         SPARK EV   CHEVROLET
22                   FOCUS ELECTRIC        FORD
23                          SOUL EV         KIA
24                           i-MiEV  MITSUBISHI
25                             LEAF      NISSAN
26  FORTWO ELECTRIC DRIVE CABRIOLET       SMART
27      FORTWO ELECTRIC DRIVE COUPE       SMART
28         MODEL S (60 kWh battery)       TESLA
29         MODEL S (70 kWh battery)       TESLA
30      MODEL S (85/90 kWh battery)       TESLA
31                      MODEL S 70D       TESLA
32                  MODEL S 85D/90D       TESLA
33                MODEL S P85D/P90D       TESLA
34                               i3         BMW
35                         SPARK EV   CHEVROLET
36                   FOCUS ELECTRIC        FORD
37                          SOUL EV         KIA
38                           i-MiEV  MITSUBISHI
39            LEAF (24 kWh battery)      NISSAN
40            LEAF (30 kWh battery)      NISSAN
41  FORTWO ELECTRIC DRIVE CABRIOLET       SMART
42      FORTWO ELECTRIC DRIVE COUPE       SMART
43         MODEL S (60 kWh battery)       TESLA
44         MODEL S (70 kWh battery)       TESLA
45      MODEL S (85/90 kWh battery)       TESLA
46                      MODEL S 70D       TESLA
47                  MODEL S 85D/90D       TESLA
48            MODEL S 90D (Refresh)       TESLA
49                MODEL S P85D/P90D       TESLA
50           MODEL S P90D (Refresh)       TESLA
51                      MODEL X 90D       TESLA
52                     MODEL X P90D       TESLA

In [33]:
df.shape

(53, 17)

In [34]:
df.items

<bound method DataFrame.iteritems of     YEAR        Make                            Model                   Size  \
0   2012  MITSUBISHI                           i-MiEV             SUBCOMPACT
1   2012      NISSAN                             LEAF               MID-SIZE
2   2013        FORD                   FOCUS ELECTRIC                COMPACT
3   2013  MITSUBISHI                           i-MiEV             SUBCOMPACT
4   2013      NISSAN                             LEAF               MID-SIZE
5   2013       SMART  FORTWO ELECTRIC DRIVE CABRIOLET             TWO-SEATER
6   2013       SMART      FORTWO ELECTRIC DRIVE COUPE             TWO-SEATER
7   2013       TESLA         MODEL S (40 kWh battery)              FULL-SIZE
8   2013       TESLA         MODEL S (60 kWh battery)              FULL-SIZE
9   2013       TESLA         MODEL S (85 kWh battery)              FULL-SIZE
10  2013       TESLA              MODEL S PERFORMANCE              FULL-SIZE
11  2014   CHEVROLET                         SPARK EV             SUBCOMPACT
12  2014        FORD                   FOCUS ELECTRIC                COMPACT
13  2014  MITSUBISHI                           i-MiEV             SUBCOMPACT
14  2014      NISSAN                             LEAF               MID-SIZE
15  2014       SMART  FORTWO ELECTRIC DRIVE CABRIOLET             TWO-SEATER
16  2014       SMART      FORTWO ELECTRIC DRIVE COUPE             TWO-SEATER
17  2014       TESLA         MODEL S (60 kWh battery)              FULL-SIZE
18  2014       TESLA         MODEL S (85 kWh battery)              FULL-SIZE
19  2014       TESLA              MODEL S PERFORMANCE              FULL-SIZE
20  2015         BMW                               i3             SUBCOMPACT
21  2015   CHEVROLET                         SPARK EV             SUBCOMPACT
22  2015        FORD                   FOCUS ELECTRIC                COMPACT
23  2015         KIA                          SOUL EV  STATION WAGON - SMALL
24  2015  MITSUBISHI                           i-MiEV             SUBCOMPACT
25  2015      NISSAN                             LEAF               MID-SIZE
26  2015       SMART  FORTWO ELECTRIC DRIVE CABRIOLET             TWO-SEATER
27  2015       SMART      FORTWO ELECTRIC DRIVE COUPE             TWO-SEATER
28  2015       TESLA         MODEL S (60 kWh battery)              FULL-SIZE
29  2015       TESLA         MODEL S (70 kWh battery)              FULL-SIZE
30  2015       TESLA      MODEL S (85/90 kWh battery)              FULL-SIZE
31  2015       TESLA                      MODEL S 70D              FULL-SIZE
32  2015       TESLA                  MODEL S 85D/90D              FULL-SIZE
33  2015       TESLA                MODEL S P85D/P90D              FULL-SIZE
34  2016         BMW                               i3             SUBCOMPACT
35  2016   CHEVROLET                         SPARK EV             SUBCOMPACT
36  2016        FORD                   FOCUS ELECTRIC                COMPACT
37  2016         KIA                          SOUL EV  STATION WAGON - SMALL
38  2016  MITSUBISHI                           i-MiEV             SUBCOMPACT
39  2016      NISSAN            LEAF (24 kWh battery)               MID-SIZE
40  2016      NISSAN            LEAF (30 kWh battery)               MID-SIZE
41  2016       SMART  FORTWO ELECTRIC DRIVE CABRIOLET             TWO-SEATER
42  2016       SMART      FORTWO ELECTRIC DRIVE COUPE             TWO-SEATER
43  2016       TESLA         MODEL S (60 kWh battery)              FULL-SIZE
44  2016       TESLA         MODEL S (70 kWh battery)              FULL-SIZE
45  2016       TESLA      MODEL S (85/90 kWh battery)              FULL-SIZE
46  2016       TESLA                      MODEL S 70D              FULL-SIZE
47  2016       TESLA                  MODEL S 85D/90D              FULL-SIZE
48  2016       TESLA            MODEL S 90D (Refresh)              FULL-SIZE
49  2016       TESLA                MODEL S P85D/P90D              FULL-SIZE
50  2016       TESLA           MODEL S P90D (Refresh)              FULL-SIZE
51  2016       TESLA                      MODEL X 90D         SUV - STANDARD
52  2016       TESLA                     MODEL X P90D         SUV - STANDARD

    (kW) Unnamed: 5 TYPE  CITY (kWh/100 km)  HWY (kWh/100 km)  \
0     49         A1    B               16.9              21.4
1     80         A1    B               19.3              23.0
2    107         A1    B               19.0              21.1
3     49         A1    B               16.9              21.4
4     80         A1    B               19.3              23.0
5     35         A1    B               17.2              22.5
6     35         A1    B               17.2              22.5
7    270         A1    B               22.4              21.9
8    270         A1    B               22.2              21.7
9    270         A1    B               23.8              23.2
10   310         A1    B               23.9              23.2
11   104         A1    B               16.0              19.6
12   107         A1    B               19.0              21.1
13    49         A1    B               16.9              21.4
14    80         A1    B               16.5              20.8
15    35         A1    B               17.2              22.5
16    35         A1    B               17.2              22.5
17   225         A1    B               22.2              21.7
18   270         A1    B               23.8              23.2
19   310         A1    B               23.9              23.2
20   125         A1    B               15.2              18.8
21   104         A1    B               16.0              19.6
22   107         A1    B               19.0              21.1
23    81         A1    B               17.5              22.7
24    49         A1    B               16.9              21.4
25    80         A1    B               16.5              20.8
26    35         A1    B               17.2              22.5
27    35         A1    B               17.2              22.5
28   283         A1    B               22.2              21.7
29   283         A1    B               23.8              23.2
30   283         A1    B               23.8              23.2
31   280         A1    B               20.8              20.6
32   280         A1    B               22.0              19.8
33   515         A1    B               23.4              21.5
34   125         A1    B               15.2              18.8
35   104         A1    B               16.0              19.6
36   107         A1    B               19.0              21.1
37    81         A1    B               17.5              22.7
38    49         A1    B               16.9              21.4
39    80         A1    B               16.5              20.8
40    80         A1    B               17.0              20.7
41    35         A1    B               17.2              22.5
42    35         A1    B               17.2              22.5
43   283         A1    B               22.2              21.7
44   283         A1    B               23.8              23.2
45   283         A1    B               23.8              23.2
46   386         A1    B               20.8              20.6
47   386         A1    B               22.0              19.8
48   386         A1    B               20.8              19.7
49   568         A1    B               23.4              21.5
50   568         A1    B               22.9              21.0
51   386         A1    B               23.2              22.2
52   568         A1    B               23.6              23.3

    COMB (kWh/100 km)  CITY (Le/100 km)  HWY (Le/100 km)  COMB (Le/100 km)  \
0                18.7               1.9              2.4               2.1
1                21.1               2.2              2.6               2.4
2                20.0               2.1              2.4               2.2
3                18.7               1.9              2.4               2.1
4                21.1               2.2              2.6               2.4
5                19.6               1.9              2.5               2.2
6                19.6               1.9              2.5               2.2
7                22.2               2.5              2.5               2.5
8                21.9               2.5              2.4               2.5
9                23.6               2.7              2.6               2.6
10               23.6               2.7              2.6               2.6
11               17.8               1.8              2.2               2.0
12               20.0               2.1              2.4               2.2
13               18.7               1.9              2.4               2.1
14               18.4               1.9              2.3               2.1
15               19.6               1.9              2.5               2.2
16               19.6               1.9              2.5               2.2
17               21.9               2.5              2.4               2.5
18               23.6               2.7              2.6               2.6
19               23.6               2.7              2.6               2.6
20               16.8               1.7              2.1               1.9
21               17.8               1.8              2.2               2.0
22               20.0               2.1              2.4               2.2
23               19.9               2.0              2.6               2.2
24               18.7               1.9              2.4               2.1
25               18.4               1.9              2.3               2.1
26               19.6               1.9              2.5               2.2
27               19.6               1.9              2.5               2.2
28               21.9               2.5              2.4               2.5
29               23.6               2.7              2.6               2.6
30               23.6               2.7              2.6               2.6
31               20.7               2.3              2.3               2.3
32               21.0               2.5              2.2               2.4
33               22.5               2.6              2.4               2.5
34               16.8               1.7              2.1               1.9
35               17.8               1.8              2.2               2.0
36               20.0               2.1              2.4               2.2
37               19.9               2.0              2.6               2.2
38               18.7               1.9              2.4               2.1
39               18.4               1.9              2.3               2.1
40               18.6               1.9              2.3               2.1
41               19.6               1.9              2.5               2.2
42               19.6               1.9              2.5               2.2
43               21.9               2.5              2.4               2.5
44               23.6               2.7              2.6               2.6
45               23.6               2.7              2.6               2.6
46               20.7               2.3              2.3               2.3
47               21.0               2.5              2.2               2.4
48               20.3               2.3              2.2               2.3
49               22.5               2.6              2.4               2.5
50               22.1               2.6              2.4               2.5
51               22.7               2.6              2.5               2.6
52               23.5               2.7              2.6               2.6

    (g/km)  RATING  (km)  TIME (h)
0        0     NaN   100         7
1        0     NaN   117         7
2        0     NaN   122         4
3        0     NaN   100         7
4        0     NaN   117         7
5        0     NaN   109         8
6        0     NaN   109         8
7        0     NaN   224         6
8        0     NaN   335        10
9        0     NaN   426        12
10       0     NaN   426        12
11       0     NaN   131         7
12       0     NaN   122         4
13       0     NaN   100         7
14       0     NaN   135         5
15       0     NaN   109         8
16       0     NaN   109         8
17       0     NaN   335        10
18       0     NaN   426        12
19       0     NaN   426        12
20       0     NaN   130         4
21       0     NaN   131         7
22       0     NaN   122         4
23       0     NaN   149         4
24       0     NaN   100         7
25       0     NaN   135         5
26       0     NaN   109         8
27       0     NaN   109         8
28       0     NaN   335        10
29       0     NaN   377        12
30       0     NaN   426        12
31       0     NaN   386        12
32       0     NaN   435        12
33       0     NaN   407        12
34       0    10.0   130         4
35       0    10.0   131         7
36       0    10.0   122         4
37       0    10.0   149         4
38       0    10.0   100         7
39       0    10.0   135         5
40       0    10.0   172         6
41       0    10.0   109         8
42       0    10.0   109         8
43       0    10.0   335        10
44       0    10.0   377        12
45       0    10.0   426        12
46       0    10.0   386        12
47       0    10.0   435        12
48       0    10.0   473        12
49       0    10.0   407        12
50       0    10.0   435        12
51       0    10.0   414        12
52       0    10.0   402        12  >

In [38]:
df.head(5)

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7

In [39]:
df.tail(5)

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [41]:
df.sample(5)

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
15,2014,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
11,2014,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6

In [42]:
df.index

RangeIndex(start=0, stop=53, step=1)

In [43]:
df.dtypes

YEAR                   int64
Make                  object
Model                 object
Size                  object
(kW)                   int64
Unnamed: 5            object
TYPE                  object
CITY (kWh/100 km)    float64
HWY (kWh/100 km)     float64
COMB (kWh/100 km)    float64
CITY (Le/100 km)     float64
HWY (Le/100 km)      float64
COMB (Le/100 km)     float64
(g/km)                 int64
RATING               float64
(km)                   int64
TIME (h)               int64
dtype: object

In [45]:
df.describe()

,YEAR,(kW),CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
count,53.000000,53.000000,53.00000,53.000000,53.000000,53.000000,53.000000,53.000000,53.0,19.0,53.000000,53.000000
mean,2014.735849,190.622642,19.64717,21.633962,20.541509,2.207547,2.422642,2.301887,0.0,10.0,239.169811,8.471698
std,1.227113,155.526429,3.00100,1.245753,1.979455,0.344656,0.143636,0.212576,0.0,0.0,141.426352,2.991036
min,2012.000000,35.000000,15.20000,18.800000,16.800000,1.700000,2.100000,1.900000,0.0,10.0,100.000000,4.000000
25%,2014.000000,80.000000,17.00000,20.800000,18.700000,1.900000,2.300000,2.100000,0.0,10.0,117.000000,7.000000
50%,2015.000000,107.000000,19.00000,21.700000,20.000000,2.100000,2.400000,2.200000,0.0,10.0,135.000000,8.000000
75%,2016.000000,283.000000,22.40000,22.500000,22.100000,2.500000,2.500000,2.500000,0.0,10.0,402.000000,12.000000
max,2016.000000,568.000000,23.90000,23.300000,23.600000,2.700000,2.600000,2.600000,0.0,10.0,473.000000,12.000000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 17 columns):
YEAR                 53 non-null int64
Make                 53 non-null object
Model                53 non-null object
Size                 53 non-null object
(kW)                 53 non-null int64
Unnamed: 5           53 non-null object
TYPE                 53 non-null object
CITY (kWh/100 km)    53 non-null float64
HWY (kWh/100 km)     53 non-null float64
COMB (kWh/100 km)    53 non-null float64
CITY (Le/100 km)     53 non-null float64
HWY (Le/100 km)      53 non-null float64
COMB (Le/100 km)     53 non-null float64
(g/km)               53 non-null int64
RATING               19 non-null float64
(km)                 53 non-null int64
TIME (h)             53 non-null int64
dtypes: float64(7), int64(5), object(5)
memory usage: 7.1+ KB

In [47]:
df.nunique()

YEAR                  5
Make                  8
Model                23
Size                  7
(kW)                 15
Unnamed: 5            1
TYPE                  1
CITY (kWh/100 km)    19
HWY (kWh/100 km)     19
COMB (kWh/100 km)    19
CITY (Le/100 km)     10
HWY (Le/100 km)       6
COMB (Le/100 km)      8
(g/km)                1
RATING                1
(km)                 19
TIME (h)              7
dtype: int64

In [48]:
df.iloc[5]

YEAR                                            2013
Make                                           SMART
Model                FORTWO ELECTRIC DRIVE CABRIOLET
Size                                      TWO-SEATER
(kW)                                              35
Unnamed: 5                                        A1
TYPE                                               B
CITY (kWh/100 km)                               17.2
HWY (kWh/100 km)                                22.5
COMB (kWh/100 km)                               19.6
CITY (Le/100 km)                                 1.9
HWY (Le/100 km)                                  2.5
COMB (Le/100 km)                                 2.2
(g/km)                                             0
RATING                                           NaN
(km)                                             109
TIME (h)                                           8
Name: 5, dtype: object